### ISSUE TITLE
No such module 'SDWebImage'

### ISSUE THREAD

**Issue by hepto** [bashirsk/MusicApp#2]
Currently getting a build issue where it can't find the SDWebImage module in `UIImageView+MA.swift:10`

I've done a `git clone` and a `pod install` before opening in Xcode 10.2.1 and trying to Run.

We use `carthage` rather than `cocoapods`, so not sure I've got everything set up correctly - anything else I should be doing?

**Comment by bashirsk** [comment]
Hi Greg, 
Could you please do a `pod update` if you have `cocoapods` installed on your machine. That should fix the issue. Please let me know if that works. Thanks.

**Comment by hepto** [comment]
Thanks @bashirsk - I was being an idiot though and I had been opening the `.xcodeproj` instead of the `.xcworkspace`! 🤦🏻‍♂️

All working now.

**Comment by bashirsk** [comment]
Cheers @hepto. No worries.
